# Build (pasa VITE_* como build-arg si construyes con docker build)
FROM node:20-alpine AS builder
WORKDIR /app
ARG VITE_FIREBASE_API_KEY
ARG VITE_FIREBASE_AUTH_DOMAIN
ARG VITE_FIREBASE_PROJECT_ID
ARG VITE_FIREBASE_STORAGE_BUCKET
ARG VITE_FIREBASE_MESSAGING_SENDER_ID
ARG VITE_FIREBASE_APP_ID
ARG VITE_TOKEN_ALTAS_BAJAS
ARG VITE_FIREBASE_PANEL_EMAIL
ARG VITE_FIREBASE_PANEL_PASSWORD
ENV VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY
ENV VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN
ENV VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID
ENV VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET
ENV VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID
ENV VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID
ENV VITE_TOKEN_ALTAS_BAJAS=$VITE_TOKEN_ALTAS_BAJAS
ENV VITE_FIREBASE_PANEL_EMAIL=$VITE_FIREBASE_PANEL_EMAIL
ENV VITE_FIREBASE_PANEL_PASSWORD=$VITE_FIREBASE_PANEL_PASSWORD
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Run
FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
RUN echo '{"type":"module"}' > package.json
COPY --from=builder /app/dist ./dist
COPY server.js ./
EXPOSE 8080
CMD ["node", "server.js"]
